### ISSUE TITLE
Can't find Bitmani Redmine Stack

### ISSUE THREAD

**Issue by bakuhachi** [takuya-takeuchi/RedArmory#31]
32bit version of Windows don't have registry key "HKLM\SOFTWARE\Wow6432Node\".

**Comment by takuya-takeuchi** [comment]
Thank you for your report!!
But I have no 32bit machine. So I have to create Hyper-V machine.
Just give me a second.

Please give me Bitnami version and Windows 10 version If you can.

**Comment by takuya-takeuchi** [comment]
I fixed this issue by #32. Please use latest release!!

**Comment by bakuhachi** [comment]
Thank you for your quick response.
