### ISSUE TITLE
Bitnami Redmine Stack not found in windows server 2016

### ISSUE THREAD

**Issue by mystster** [takuya-takeuchi/RedArmory#35]
windows server  2016 上で動かしたところ、bitnami redmine stack が見つかりませんでした。レジストリエディタで確認したところ、以下のレジストリが使われていました。
@"SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall"

windows server 2016は動作環境に入っていませんが、ご参考までに連絡いたします。

ソースを変更したところ正常に動作しているようです。

**Comment by takuya-takeuchi** [comment]
@mystster 
ありがとうございます
参考までにbitnami  redmine stack のバージョンを教えていただけないでしょうか？

**Comment by mystster** [comment]
再度確認したところ、64bit版をインストールしたためのように思います。
が、BitnamiのWebからは32bit版はダウンロードできない？ようです。

使ったバージョンは4.0.4-5 64bitです。
本日(2019/10/15)現在の最新版です。
https://bitnami.com/stack/redmine/installer

**Comment by mystster** [comment]
ご参考までですが、Windows Server 2012の環境で3.4.5-0を使用していたときは問題なく動作していました。

**Comment by takuya-takeuchi** [comment]
@mystster 
貴重な情報ありがとうございます
4系から64bit になったのでしょうか？
修正方法を検討してみます

**Comment by takuya-takeuchi** [comment]
4.0.0は**bitnami-redmine-4.0.0-0-windows-installer.exe**があることが判明。

**Comment by takuya-takeuchi** [comment]
Windows Server 2016 64bitに下記をインストールしてレジストリを確認

## 4.0.4-5 64bit
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Bitnami Redmine Stack 4.0.4-5

## 4.0.0-0 64bit
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Bitnami Redmine Stack 4.0.0-0

## 3.4.6-5 32bit
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Bitnami Redmine Stack 3.4.6-5

**Comment by takuya-takeuchi** [comment]
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall

の両方を探索することで対応する

**Comment by takuya-takeuchi** [comment]
![image](https://user-images.githubusercontent.com/6241854/67102627-b90af100-f1fe-11e9-988b-071ada54a519.png)

**Comment by mystster** [comment]
早速のご対応ありがとうございます。
今手元に環境がないため試せないのですが、たしかサービスが登録されているレジストリも64bitになっていたかと思います。ご確認いただけると助かります。

**Comment by takuya-takeuchi** [comment]
![image](https://user-images.githubusercontent.com/6241854/67152730-d8e20800-f317-11e9-9a41-3bc2708d00dc.png)

サービスの情報自体は32/64無関係に同じ個所にありますね。
**HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\redmineXXXXX**

**Comment by mystster** [comment]
ご確認ありがとうございます。
この部分は問題にならないでしょうか？手元(2016)ではWow6432Nodeが存在していなかったので、このままのコードでは動作いないと思ったのですが。

https://github.com/takuya-takeuchi/RedArmory/blob/584f7e472b3602dc098e6e3e75bb1a62d35d7c2a/source/RedArmory/Models/Services/BitNamiRedmineService.cs#L226-L228

**Comment by takuya-takeuchi** [comment]
@mystster 
返信が遅くなり申し訳ありません。
そちらのメソッドは現在使用しておりませんので問題ありません。

**Comment by mystster** [comment]
わかりました。ご対応ありがとうございました。
